### ISSUE TITLE
Bun error: `Node-API function "napi_type_tag_object" is not implemented yet`

### ISSUE THREAD

**Issue by awilderink** [tursodatabase/libsql-js#102]
Not sure if this is a `bun` or a `libsql` issue, but in earlier versions `0.3.10` this issue did not appear. A workaround is to lock the libsql version to `0.3.10` in your `package.json`.

**Comment by rphsoftware** [comment]
I just checked and it seems like this issue starts occuring on version `0.3.13`, when it didn't occur on `0.3.12`. Diff: https://github.com/tursodatabase/libsql-js/compare/v0.3.12...v0.3.13
My theory is that the Neon update might be the culprit here, but I am not 100% certain on that.

**Comment by rphsoftware** [comment]
Follow-up on my comment: Building the `libsql-js` cargo project with the following:

```toml
[dependencies.neon]
version = "1.0.0"
default-features = false
features = ["napi-6"]
```

Seems to make it work again in bun. I am not in a position where I can easily open a PR right now, but if this change doesn't harm any other part it should be an easy fix.

**Comment by rphsoftware** [comment]
I just verified with my codebase, bun now works again on local databases starting with `0.3.17` (after ensuring it's up to date and the dependency is not stale, i recommend clearing `~/.bun`, deleting `node_modules` and `bun.lockb`), i guess this issue can be closed now

**Comment by penberg** [comment]
Fixed by https://github.com/tursodatabase/libsql-js/pull/105, right @rphsoftware?

**Comment by awilderink** [comment]
Confirmed, this can be closed now! Thanks everybody
