### ISSUE TITLE
Make sync read-your-write guarantee optional

### ISSUE THREAD

**Issue by penberg** [tursodatabase/libsql-js#110]
We turn on read-your-write guarantee now unconditionally, but in some use cases that's not desirable. Let's make it configurable.

**Comment by khuezy** [comment]
Hi! I would still like to read-my-write but can the sync be done in a separate thread? I've noticed that after I write, my (node) server is blocked until the write finishes. Ref to discussion: https://discord.com/channels/933071162680958986/1265128069715464223

**Comment by khuezy** [comment]
hmm okay, I'll wait for this to be released to see if it fixes the read latency immediately after a write.

**Comment by haaawk** [comment]
@khuezy you should be able to use opts.readYourWrites = false to get better performance now

**Comment by khuezy** [comment]
@haaawk has the "@libsql/client" been updated w/ this new config?

**Comment by haaawk** [comment]
Not yet. It will be in the next release @khuezy

**Comment by robinjonsson** [comment]
@haaawk I tested with @libsql/client 0.9.0, but readYourWrites is not available yet. It would be great to have support for this in @libsql/client, as read-your-writes becomes very slow when performing multiple writes.
