### ISSUE TITLE
Query timing support

### ISSUE THREAD

**Issue by penberg** [tursodatabase/libsql-js#122]
We need an API for clients to check how long an individual query took because for the async API in particular it's hard to do on application side.

For `Statement.run()`, we can piggy-bank on the info object that's part of `better-sqlite3` and just add a `duration` field that returns query duration in seconds there:

```
const stmt = await db.prepare('INSERT INTO cats (name, age) VALUES (?, ?)');
const info = await stmt.run('Joey', 2);

console.log(info.duration); // => 0.01
```

For `Statement.get()` and `Statement.all()`, let's consider a `_metadata` field with `duration` to avoid conflicting with SQL column names:

```
const stmt = db.prepare('SELECT age FROM cats WHERE name = ?');
const cat = stmt.get('Joey');

console.log(cat._metadata.duration); // => 0.01

const stmt = db.prepare('SELECT * FROM cats WHERE name = ?');
const cats = stmt.all('Joey');

console.log(cats._metadata.duration); // => 0.01
```

If query duration tracking has performance overhead, we need to also make it a configuration option.

**Comment by abidta** [comment]
Hi, I'd like to work on this issue.

**Comment by zen0wu** [comment]
would be great to also expose something for `iterate()`, similarly maybe on every step we could return a duration in _metadata
