### ISSUE TITLE
Bundler support is broken

### ISSUE THREAD

**Issue by hugo082** [tursodatabase/libsql-js#70]
I used the package in a lambda built via sst & esbuild. It seems the dependency is not included inside the output bundle.

```
Error: Cannot find module '@libsql/darwin-arm64'
```

<img width="1382" alt="image" src="https://github.com/tursodatabase/libsql-js/assets/12221094/9a99c990-b9d2-46d4-9318-4d89575d2b05">

I see that there is a special line to force bundlers to include the dependency, but the file `./targets` seems to be missing, maybe it's related?

https://github.com/tursodatabase/libsql-js/blob/6e705ac5d9595cc969149e208e0a9a1d9fb877b0/index.js#L6-L9

**Comment by hugo082** [comment]
I fixed the issue by putting the package as [`external`](https://esbuild.github.io/api/#external).

```ts
{
  nodejs: {
    esbuild: {
      external: ['libsql'],
    },
  },
},
```

**Comment by yspreen** [comment]
and then you just copied over the libsql folder to your lambda dist?

**Comment by yspreen** [comment]
Marking it as external does not work for me:

```
2024-03-26T02:55:52.789Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'libsql'\nRequire stack:\n- /var/task/lambda.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'libsql'",
        "Require stack:",
        "- /var/task/lambda.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}

```
